### ISSUE TITLE
apriltag.c: No tag families enabled

### ISSUE THREAD

**Issue by khajash** [swatbotics/apriltag#2] opened 2018-04-13 18:45 UTC
I'm running into an issue where it can find the library. I'm using the standard tag36h11 family, but it still raises the same issue. It seems like it's a pointer issue, but I don't know any C++ so I'm having difficulty troubleshooting it. 
Any feedback would be greatly appreciated. 
Thanks!

**Comment by mzucker** [comment] 2018-06-22 20:49
Closing this issue since it doesn't supply sufficient detail to investigate and reproduce. If you're still having problems, consider filing a new issue that has at least the following information:

 - what compiler and architecture you are using
 - whether the issue happens during compilation or at runtime
 - what program you are running/building (your code or one of the example codes)

Thanks!

**Closed by mzucker** 2018-06-22 20:49 UTC
